In [1]:
import re
import string

# !pip install -U nltk

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import sent_tokenize # Sentence Tokenizer
from nltk.tokenize import word_tokenize # Word Tokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.probability import FreqDist

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from urllib.request import urlopen
import requests
from bs4 import BeautifulSoup


[nltk_data] Downloading package punkt to /home/superio/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/superio/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# 1) (optional) Scrape 100 Job Listings that contain the title "Data Scientist" from indeed.com

At a minimum your final dataframe of job listings should contain
- Job Title
- Job Description

In [2]:
df = pd.read_csv("job_listings.csv").drop(columns=["Unnamed: 0"])
df

description  \
0    b"<div><div>Job Requirements:</div><ul><li><p>...   
1    b'<div>Job Description<br/>\n<br/>\n<p>As a Da...   
2    b'<div><p>As a Data Scientist you will be work...   
3    b'<div class="jobsearch-JobMetadataHeader icl-...   
4    b'<ul><li>Location: USA \xe2\x80\x93 multiple ...   
5    b'<div>Create various Business Intelligence An...   
6    b'<div><p>As Spotify Premium swells to over 96...   
7    b"Everytown for Gun Safety, the nation's large...   
8    b"<ul><li>MS in a quantitative discipline such...   
9    b'<div><p>Slack is hiring experienced data sci...   
10   b'<div><p><b>Who We Are</b></p><p>\nBlackThorn...   
11   b'<div class="jobsearch-JobMetadataHeader icl-...   
12   b"nfosys\xe2\x80\x93 Data &amp; Analytics \xe2...   
13   b'<div><p>As Spotify Premium swells to over 96...   
14   b'<div><ul><li>Experience with guiding R&amp;D...   
15   b'<div><p>The Atlantic is seeking a Data Scien...   
16   b'<div><p><b>THE CHALLENGE</b></p><p>\nEventbr...   
17   b'<div class="jobsearch-JobMetadataHeader icl-...   
18   b"Everytown for Gun Safety, the nation's large...   
19   b'<div class="jobsearch-JobMetadataHeader icl-...   
20   b'<div class="jobsearch-JobMetadataHeader icl-...   
21   b'<b>The Challenge:</b><br/>\nAre you excited ...   
22   b'<div><p>We are seeking a Data Scientist to j...   
23   b'<div><div><div>Motiion is a technology and d...   
24   b'<div><div><div><p>The Scientist is responsib...   
25   b"As a Data Scientist for Ads Measurement in t...   
26   b'<div><div><div><div><p>Summary</p><div><div>...   
27   b'<div><p>Slack is looking for experienced dat...   
28   b"nfosys\xe2\x80\x93 Data &amp; Analytics \xe2...   
29   b'<div class="jobsearch-JobMetadataHeader icl-...   
..                                                 ...   
396  b"ABOUT US\n<br/>Lark is the world's largest A...   
397  b'<div><p>Zenreach solves a major problem for ...   
398  b'<div><p><b>Position Description</b></p><br/>...   
399  b'By trade we are a technology company, but if...   
400  b'<div><b>Purpose &amp; Overall Relevance for ...   
401  b"<div><p><b>about dscout</b></p>\n<p>We are d...   
402  b"<div><div><b>Junior Data Scientist - Big Dat...   
403  b"About Us\n<br/>Interested in working for a h...   
404  b'<div>Air Products, Inc., a Fortune 500 manuf...   
405  b"<div>Data Scientist -<br/>\nDo you want the ...   
406  b'<div><b>Job Description:</b><br/>\n<p><b>Dat...   
407  b'<div><div><div><div><div>The Data Scientist ...   
408  b'<div><p>FinLocker is a leading financial dat...   
409  b'<div><p>With annual sales of $15 billion, Ec...   
410  b'<div>Job Description:<br/>\n<br/>\nThe Enter...   
411  b"<div>Description:\n<p>Chicago - IL, IL150SW,...   
412  b'<div>Nike Supply Chain experts ensure that e...   
413  b'<div><div>The Principal Data Scientist is re...   
414  b'<div><p>We are looking for a Senior Data Sci...   
415  b'<div class="jobsearch-JobMetadataHeader icl-...   
416  b'<div></div><div><div><div><div><div><div>Los...   
417  b'<div><b><i>About the Role...</i></b><br/>\n<...   
418  b'<div class="jobsearch-JobMetadataHeader icl-...   
419  b'<div><ul><li>Bachelor\xe2\x80\x99s or Master...   
420  b'<div><div>At Uber, we ignite opportunity by ...   
421  b"<b>About Us:</b><br/>\nWant to be part of a ...   
422  b'<div class="jobsearch-JobMetadataHeader icl-...   
423  b'<div class="jobsearch-JobMetadataHeader icl-...   
424  b"<p></p><div><p>SENIOR DATA SCIENTIST</p><p>\...   
425  b'<div></div><div><div><div><div><p>Cerner Int...   

                                                 title  
0                                      Data scientist   
1                                     Data Scientist I  
2                         Data Scientist - Entry Level  
3                                       Data Scientist  
4                                       Data Scientist  
5                                       Data Scientist  
6         Associate Data Scientist – Premium An

## 2) Use NLTK to tokenize / clean the listings 

In [3]:
# Removing numbers and comma before description text
df.description = df.description.str.lstrip('1234567890,').str.strip('b\"\'')
df.description = df.description.str.replace('<[^<]+?>', '')
df.description = df.description.replace('\n','', regex=False)
df.description = df.description.apply(lambda x:x.replace('\\n', ' '))
df.description = df.description.apply(lambda x:x.replace('\xe2\x80\x93', ' '))

In [4]:
# FROM LECTURE
import string
table = str.maketrans('','', string.punctuation)
stop_words = set(stopwords.words('english'))

def tokenize(texts):
    # Tokenize by word
    tokens = word_tokenize(texts)
#     print("Tokens:", tokens)
    # Make all words lowercase
    lowercase_tokens = [w.lower() for w in tokens]
#     print("Lowercase:", lowercase_tokens)
    # Strip punctuation from within words
    no_punctuation = [x.translate(table) for x in lowercase_tokens]
#     print("No Punctuation:", no_punctuation)
    # Remove words that aren't alphabetic
    alphabetic = [word for word in no_punctuation if word.isalpha()]
#     print("Alphabetic:", alphabetic)
    # Remove stopwords
    words = [w for w in alphabetic if not w in stop_words]
#     print("Cleaned Words:", words)
    return words

df['tokenized_description'] = df['description'].apply(tokenize)
df['tokenized_title'] = df['title'].apply(tokenize)

df

description  \
0    Job Requirements: Conceptual understanding in ...   
1    Job Description  As a Data Scientist 1, you wi...   
2    As a Data Scientist you will be working on con...   
3    $4,969 - $6,756 a monthContractUnder the gener...   
4    Location: USA \xe2\x80\x93 multiple locations ...   
5    Create various Business Intelligence Analytica...   
6    As Spotify Premium swells to over 96M subscrib...   
7    Everytown for Gun Safety, the nation's largest...   
8    MS in a quantitative discipline such as Statis...   
9    Slack is hiring experienced data scientists to...   
10   Who We Are BlackThorn Therapeutics is a comput...   
11   Part-timeAbout The Opportunity Here at Grubhub...   
12   nfosys\xe2\x80\x93 Data &amp; Analytics \xe2\x...   
13   As Spotify Premium swells to over 96M subscrib...   
14   Experience with guiding R&amp;D strategy for y...   
15   The Atlantic is seeking a Data Scientist to he...   
16   THE CHALLENGE Eventbrite is big, bustling mark...   
17   ContractWe are looking to hire for a Data Scie...   
18   Everytown for Gun Safety, the nation's largest...   
19   $70,000 - $100,000 a yearTitle: Data Analyst/J...   
20   $45,000 a yearWorking under direction of the A...   
21   The Challenge: Are you excited at the prospect...   
22   We are seeking a Data Scientist to join our Pr...   
23   Motiion is a technology and data company for t...   
24   The Scientist is responsible for the scientifi...   
25   As a Data Scientist for Ads Measurement in the...   
26   Summary Posted: Mar 6, 2019 Weekly Hours: 40 R...   
27   Slack is looking for experienced data scientis...   
28   nfosys\xe2\x80\x93 Data &amp; Analytics \xe2\x...   
29   Part-time, InternshipSUMMARY:   Sierra Nevada\...   
..                                                 ...   
396  ABOUT US Lark is the world's largest A.I. heal...   
397  Zenreach solves a major problem for brick-and-...   
398  Position Description As the Walmart Voice Comm...   
399  By trade we are a technology company, but if y...   
400  Purpose &amp; Overall Relevance for the Organi...   
401  about dscout We are dscout. At our core, we ar...   
402  Junior Data Scientist - Big Data (Entry-Level)...   
403  About Us Interested in working for a human-cen...   
404  Air Products, Inc., a Fortune 500 manufacturer...   
405  Data Scientist - Do you want the opportunity t...   
406  Job Description: Data Scientist Interactive He...   
407  The Data Scientist I mines and analyzes comple...   
408  FinLocker is a leading financial data and anal...   
409  With annual sales of $15 billion, Ecolab (ECL)...   
410  Job Description:  The Enterprise Data Solution...   
411  Description: Chicago - IL, IL150SW, 150 S Wack...   
412  Nike Supply Chain experts ensure that every ye...   
413  The Principal Data Scientist is responsible fo...   
414  We are looking for a Senior Data Scientist wit...   
415  Temporary, Internship The Marketing Data Scien...   
416  Los Gatos, California Science and Analytics Th...   
417  About the Role...  Logic2020 is looking to sec...   
418  ContractThe role is largely operational and su...   
419  Bachelor\xe2\x80\x99s or Master\xe2\x80\x99s d...   
420  At Uber, we ignite opportunity by setting the ...   
421  About Us: Want to be part of a fantastic and f...   
422  InternshipAt Uber, we ignite opportunity by se...   
423  $200,000 - $350,000 a yearA million people a y...   
424  SENIOR DATA SCIENTIST JOB DESCRIPTION  ABOUT U...   
425  Cerner Intelligence is a new, innovative organ...   

                                                 title  \
0                                      Data scientist    
1                                     Data Scientist I   
2                         Data Scientist - Entry Level   
3                                       Data Scientist   
4                                       Data Scientist   
5                                       Data Scientist   
6         Associate Data Scientist – Pre

# 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [5]:
nltk.download('wordnet')
from nltk.stem.wordnet import WordNetLemmatizer

# FROM LECTURE
# lemmatize
################################ 
lemmatizer = WordNetLemmatizer()
lemmatized_listings = []
for listing in [i for i in df.tokenized_description]:
    lemmas = [lemmatizer.lemmatize(word) for word in listing]
    lemmatized_listings.append(lemmas)

# List of document strings as text
lemmatized_listings

# Instantiate vectorizer object
vectorizer = CountVectorizer()
# Create a vocabulary and get word counts per document
bag_of_words = vectorizer.fit_transform(lemmatized_listings[0])
# Print word counts
print(bag_of_words.toarray())

# Get feature names to use as dataframe column headers
feature_names = vectorizer.get_feature_names()

df = pd.DataFrame(bag_of_words.toarray(), columns=feature_names)
df.head()

[nltk_data] Downloading package wordnet to /home/superio/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


ability  along  apply  apriori  article  bayes  clean  coding  communicate  \
0        0      0      0        0        0      0      0       0            0   
1        0      0      0        0        0      0      0       0            0   
2        0      0      0        0        0      0      0       0            0   
3        0      0      0        0        0      0      0       0            0   
4        0      0      0        0        0      0      0       0            0   

   conceptual  ...  stake  statisticsmathematicscomputer  svm  technical  \
0           0  ...      0                              0    0          0   
1           0  ...      0                              0    0          0   
2           1  ...      0                              0    0          0   
3           0  ...      0                              0    0          0   
4           0  ...      0                              0    0          0   

   tidyr  tree  understanding  via  work  write  
0      0     0              0    0     0      0  
1      0     0              0    0     0      0  
2      0     0              0    0     0      0  
3      0     0              1    0     0      0  
4      0     0              0    0     0      0  

[5 rows x 78 columns]

# 4) Visualize the most common word counts

In [6]:
from nltk.probability import FreqDist

fdist = FreqDist(lemmatized_listings[0])
print(fdist)

fdist.most_common(20)

import matplotlib.pyplot as plt
fdist.plot(30, cumulative=False)
plt.show()

<FreqDist with 79 samples and 83 outcomes>


 # 5) Use Scikit-Learn's tfidfVectorizer to get a TF-IDF feature matrix

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# List of document strings as text
text = lemmatized_listings[0]
# Instantiate vectorizer object
tfidf = TfidfVectorizer(max_features = 20)
# Create a vocabulary and get word counts per document
feature_matrix = tfidf.fit_transform(text)
# Print word counts
print(feature_matrix.toarray())

# Get feature names to use as dataframe column headers
feature_names = tfidf.get_feature_names()

# View Feature Matrix as DataFrame
df = pd.DataFrame(feature_matrix.toarray(), columns=feature_names)
df.head()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


ability  experience  like  master  matplotlib  model  must  neural  \
0      0.0         0.0   0.0     0.0         0.0    0.0   0.0     0.0   
1      0.0         0.0   0.0     0.0         0.0    0.0   0.0     0.0   
2      0.0         0.0   0.0     0.0         0.0    0.0   0.0     0.0   
3      0.0         0.0   0.0     0.0         0.0    0.0   0.0     0.0   
4      0.0         0.0   0.0     0.0         0.0    0.0   0.0     0.0   

   nontechnical  numpy  package  panda  past  programming  published  python  \
0           0.0    0.0      0.0    0.0   0.0          0.0        0.0     0.0   
1           0.0    0.0      0.0    0.0   0.0          0.0        0.0     0.0   
2           0.0    0.0      0.0    0.0   0.0          0.0        0.0     0.0   
3           0.0    0.0      0.0    0.0   0.0          0.0        0.0     0.0   
4           0.0    0.0      0.0    0.0   0.0          0.0        0.0     0.0   

   pythonr  quant  random  regression  
0      0.0    0.0     0.0         0.0  
1      0.0    0.0     0.0         0.0  
2      0.0    0.0     0.0         0.0  
3      0.0    0.0     0.0         0.0  
4      0.0    0.0     0.0         0.0

## Stretch Goals

 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.