<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Document Classification
## *Data Science Unit 4 Sprint 1 Lesson 3*

Today's lesson will be different. You already know how to do classification. You ready know how to extract features from documents. So? That means you're ready to combine and practice those skills in a kaggle competition. We we will open with a five minute sprint explaining the competition, and then give you 25 minutes to work. After those twenty five minutes are up, I will give a 5-minute demo an NLP technique that will help you with document classification (*and **maybe** the competition*). 

Today's all about having fun and practicing your skills.

## Learning Objectives
* <a href="#p0">Part 0</a>: Kaggle Competition
* <a href="#p1">Part 1</a>: Text Feature Extraction & Classification Pipelines
* <a href="#p2">Part 2</a>: Latent Semantic Indexing
* <a href="#p3">Part 3</a>: Word Embeddings with Spacy

## Kaggle competition

### Load in the data

In [23]:
import pandas as pd

In [190]:
train = pd.read_csv('./ds4-which-whisk/train.csv')
test = pd.read_csv('./ds4-which-whisk/test.csv')
sample_submission = pd.read_csv('./ds4-which-whisk/sample_submission.csv')

### Explore

In [26]:
train.head()

id                author  \
0   1          John Hansell   
1   2            Dave Broom   
2   3          John Hansell   
3   4          John Hansell   
4   6  Davin de Kergommeaux   

                                         description    price  ratingValue  \
0  A marriage of 13 and 18 year old bourbons. A m...     85.0           97   
1  There have been some legendary Bowmores from t...  13500.0           97   
2  This bottling celebrates master distiller Park...    150.0           97   
3  What impresses me most is how this whisky evol...   4500.0           97   
4  After 40 years in barrels, the trademark Canad...    199.0           96   

   pert_alcohol  category  
0          51.5       2.0  
1          42.9       1.0  
2          50.0       2.0  
3          40.5       1.0  
4          45.0       NaN

In [27]:
train.shape

(2874, 7)

In [28]:
train.describe()

id         price  ratingValue  pert_alcohol     category
count  2874.000000   2811.000000  2874.000000   2814.000000  2586.000000
mean   2075.814544    225.297937    86.361517     48.043019     1.637664
std    1177.805945    990.619608     4.511554      6.298527     0.963049
min       1.000000      7.500000    60.000000     33.000000     1.000000
25%    1087.250000     50.000000    84.000000     43.300000     1.000000
50%    2109.500000     80.000000    87.000000     46.000000     1.000000
75%    3102.000000    140.000000    90.000000     51.375000     2.000000
max    4157.000000  26650.000000    97.000000     98.600000     4.000000

In [30]:
# looks like we have a duplicate description
train.describe(exclude='number')

author                                        description
count           2874                                               2874
unique            12                                               2871
top     John Hansell  Swiss-based Chapter 7 released this 19 year ol...
freq             992                                                  2

In [31]:
# some null values (~60) for price and pert_alcohol
# 288 null values in category
train.isnull().sum()

id                0
author            0
description       0
price            63
ratingValue       0
pert_alcohol     60
category        288
dtype: int64

In [35]:
#example description
train['description'][0]

'A marriage of 13 and 18 year old bourbons. A mature yet very elegant whiskey, with a silky texture and so easy to embrace with a splash of water. Balanced notes of honeyed vanilla, soft caramel, a basket of complex orchard fruit, blackberry, papaya, and a dusting of cocoa and nutmeg; smooth finish. Sophisticated, stylish, with well-defined flavors. A classic!'

In [37]:
# something odd about the labels
from sklearn import svm

## Create pipeline

In [238]:
vect = TfidfVectorizer(stop_words='english')
cvect = CountVectorizer()
lsvm = svm.LinearSVC()
mnb = MultinomialNB()

pipe = Pipeline([('vect', vect), ('clf', mnb)])

In [192]:
train_clean = train[train['category'].isnull()==False]
train_clean.shape

(2586, 7)

In [132]:
pipe.fit(train_clean['description'], train_clean['category'])

Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.7, max_features=1825, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...max_iter=500,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [133]:
preds = pipe.predict(test['description'])

In [134]:
preds

array([2., 2., 4., 1., 1., 1., 1., 1., 2., 1., 4., 4., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 4., 2., 1., 1.,
       1., 1., 1., 3., 4., 3., 2., 1., 1., 3., 1., 1., 1., 2., 1., 1., 3.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 4., 2., 3.,
       1., 1., 1., 3., 1., 1., 4., 1., 3., 2., 1., 1., 4., 2., 2., 1., 1.,
       3., 2., 4., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 4., 3., 1., 1.,
       1., 2., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 1., 2., 1., 1., 1., 1., 2., 2., 4., 1., 1., 1., 1., 3., 2.,
       1., 1., 1., 1., 1., 3., 2., 1., 1., 3., 4., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 2., 2.,
       1., 3., 3., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.,
       4., 1., 3., 1., 4., 1., 1., 2., 2., 1., 1., 2., 1., 1., 1., 1., 2.,
       1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 2., 1., 1., 1., 1., 1., 1.,
       4., 2., 2., 2., 2.

In [135]:
sample_submission.head()

id  category
0   955       1.0
1  3532       1.0
2  1390       1.0
3  1024       1.0
4  1902       1.0

In [136]:
sample_submission['category'] = preds
sample_submission.head()

id  category
0   955       2.0
1  3532       2.0
2  1390       4.0
3  1024       1.0
4  1902       1.0

In [137]:
sample_submission['category'] = sample_submission['category'].apply(lambda x: int(x))
sample_submission.head()

id  category
0   955         2
1  3532         2
2  1390         4
3  1024         1
4  1902         1

In [138]:
sinclair_sub_1 = sample_submission
sinclair_sub_1.to_csv('sinclair_sub_2', index=False)

## Tuning parameters

### Grid Search

In [260]:
parameters = {
    'vect__max_df': (.275, .28, .29),
    'vect__min_df': (21, 22, 23),
    'vect__max_features': (725, 750, 775),
#     'clf__C': (1, 1.45, 1.5),
#     'clf__max_iter': (500, 1000)
}

In [261]:
grid_search = GridSearchCV(pipe,parameters, cv=5, n_jobs=-1, verbose=1)

In [262]:
grid_search.fit(train_clean['description'], train_clean['category'])

Fitting 5 folds for each of 27 candidates, totalling 135 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    8.9s
[Parallel(n_jobs=-1)]: Done 135 out of 135 | elapsed:   25.9s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'vect__max_df': (0.275, 0.28, 0.29), 'vect__min_df': (21, 22, 23), 'vect__max_features': (725, 750, 775)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [263]:
grid_search.best_params_

{'vect__max_df': 0.275, 'vect__max_features': 725, 'vect__min_df': 22}

In [264]:
grid_search.best_score_

0.8894044856921887

In [236]:
grid_preds = grid_search.predict(test['description'])
grid_preds

array([2., 2., 4., 1., 1., 1., 1., 1., 2., 1., 4., 4., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 4., 2., 1., 1.,
       1., 1., 1., 3., 4., 3., 2., 1., 1., 3., 1., 1., 1., 2., 1., 1., 3.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 4., 2., 3.,
       1., 1., 1., 3., 1., 1., 4., 1., 3., 2., 1., 1., 4., 2., 2., 1., 1.,
       3., 2., 4., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 4., 3., 1., 1.,
       1., 2., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 1., 2., 1., 1., 1., 1., 2., 2., 4., 1., 1., 1., 1., 3., 2.,
       1., 1., 1., 1., 1., 3., 2., 1., 1., 3., 4., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 2., 2.,
       1., 3., 3., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.,
       4., 1., 3., 1., 4., 1., 1., 2., 2., 1., 1., 2., 1., 1., 1., 1., 2.,
       1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 2., 1., 1., 1., 1., 1., 1.,
       4., 2., 2., 2., 2.

In [237]:
create_sub(grid_preds, 10)

## Latent Semantic Indexing
<a id="p2"></a>

In [140]:
# Import

from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=100, 
                   algorithm='randomized',
                   n_iter=10)

In [141]:
# LSI

lsi = Pipeline([('vect', vect), ('svd', svd)])

In [142]:
# Pipe

lsi_pipe = Pipeline([('lsi', lsi), ('clf', lsvm)])

In [ ]:
# getting a syntax error here, also not sure what the parameter is
params = {
    'lsi__vect__max_df':
}

In [148]:
# Fit
lsi_pipe.fit(train_clean['description'], train_clean['category'])

Pipeline(memory=None,
     steps=[('lsi', Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.7, max_features=1825, min_df=1,
        ngram_range=(1, 1), norm=...max_iter=500,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [149]:
preds = lsi_pipe.predict(test['description'])

In [150]:
preds

array([2., 2., 1., 1., 1., 1., 1., 1., 2., 1., 4., 4., 1., 1., 1., 1., 1.,
       1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 4., 2., 1., 1.,
       1., 1., 1., 3., 4., 3., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 3.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 4., 2., 1.,
       1., 1., 1., 3., 1., 1., 4., 1., 3., 2., 1., 1., 4., 2., 2., 1., 1.,
       3., 2., 4., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 4., 3., 1., 1.,
       1., 2., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 1., 2., 1., 1., 1., 1., 2., 2., 4., 1., 1., 1., 1., 3., 2.,
       1., 1., 1., 1., 1., 3., 2., 1., 1., 3., 4., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 2., 2.,
       1., 3., 3., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.,
       4., 1., 3., 1., 4., 1., 1., 2., 3., 1., 1., 2., 1., 1., 1., 1., 3.,
       1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 2., 1., 1., 1., 1., 1., 1.,
       4., 2., 2., 2., 2.

In [151]:
sample_submission['category'] = preds
sample_submission['category'] = sample_submission['category'].apply(lambda x: int(x))
sample_submission.to_csv('sinclair_sub_3', index=False)

In [179]:
def create_sub(preds, num):
    # write predictions over category feature in sample_submission
    sample_submission['category'] = preds
    sample_submission['category'] = sample_submission['category'].apply(lambda x: int(x))
    
    # create file name
    file_name = 'sinclair_submission_' + str(num)
    
    # write to csv
    sample_submission.to_csv(file_name, index=False)

## Word Embeddings with Spacy
<a id="p3"></a>

In [152]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [17]:
doc = nlp("Two bananas in pyjamas")

In [18]:
bananas_vector = doc.vector
print(len(bananas_vector))

300


In [164]:
sgdc = SGDClassifier()

In [19]:
def get_word_vectors(docs):
    return [nlp(doc).vector for doc in docs]

In [167]:
X_train = get_word_vectors(train_clean['description'])
X_test = get_word_vectors(test['description'])

In [172]:
type(X_train)

list

In [161]:
len(train_clean)

2586

In [162]:
len(X[0])

300

In [168]:
sgdc.fit(X_train, train_clean['category'])

/Users/stephensinclair/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=None,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [169]:
preds = sgdc.predict(X_test)

In [170]:
preds

array([2., 2., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 4., 2., 1., 1.,
       1., 1., 2., 3., 4., 3., 2., 1., 1., 3., 1., 1., 1., 2., 1., 1., 3.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 2., 1., 1., 4., 2., 2.,
       1., 1., 1., 3., 1., 1., 4., 1., 2., 2., 1., 1., 1., 2., 2., 1., 1.,
       3., 2., 4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 3., 3., 1., 1.,
       1., 2., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 3., 2., 1., 1., 1., 1., 2., 2., 3., 1., 1., 1., 1., 3., 2.,
       1., 1., 1., 1., 1., 3., 2., 1., 1., 3., 3., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 3., 1., 1., 1., 4., 1., 4., 1., 1., 1., 3., 1., 2., 3.,
       1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 3., 2.,
       4., 1., 3., 1., 1., 2., 1., 2., 3., 1., 1., 2., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 2., 2., 2., 2.

In [171]:
sample_submission['category'] = preds
sample_submission['category'] = sample_submission['category'].apply(lambda x: int(x))
sample_submission.to_csv('sinclair_sub_4', index=False)

## Naive Bayes

In [173]:
from sklearn.naive_bayes import MultinomialNB

In [193]:
tfidf_vect = TfidfVectorizer(stop_words='english', max_features=1825, max_df=0.9)
mnb = MultinomialNB()

nb_pipe = Pipeline([('vect', tfidf_vect), ('clf', mnb)])

In [194]:
nb_pipe.fit(train_clean['description'], train_clean['category'])

Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.9, max_features=1825, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [195]:
nb_preds = nb_pipe.predict(test['description'])

In [196]:
nb_preds

array([2., 3., 1., 1., 1., 1., 1., 1., 2., 1., 4., 4., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 4., 1., 1., 1.,
       1., 1., 1., 3., 4., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 3.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 4., 2., 1.,
       1., 1., 1., 3., 1., 1., 4., 1., 3., 2., 1., 1., 1., 2., 2., 1., 1.,
       3., 2., 4., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 4., 3., 1., 1.,
       1., 2., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 3., 2.,
       1., 1., 1., 1., 1., 3., 1., 1., 1., 3., 4., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 4., 1., 1., 1., 3., 1., 2., 2.,
       1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       4., 1., 1., 1., 4., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 2.,
       1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 2., 2., 2., 2.

In [197]:
create_sub(nb_preds, 7)

In [198]:
#imports
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

In [208]:
#Split data into train and test sets
X_train, X_val, y_train, y_val = train_test_split(train_clean['description'],
                                                    train_clean['category'],
                                                    random_state=42, test_size=.1)

In [219]:
#Train and evaluate the model
vect = CountVectorizer().fit(X_train)
X_train_vectorized = vect.transform(X_train)
clfrNB = MultinomialNB(alpha = 0.1)
clfrNB.fit(X_train_vectorized, y_train)
val_preds = clfrNB.predict(vect.transform(X_val))
# score = roc_auc_score(y_test, preds)
# print(score)
# #0.9720812182741116

In [220]:
len(val_preds)

259

In [223]:
type(y_val)

pandas.core.series.Series

In [216]:
create_sub(preds, 8)

In [217]:
from sklearn.metrics import classification_report

In [225]:
print(classification_report(val_preds, y_val))

              precision    recall  f1-score   support

         1.0       0.97      0.98      0.98       151
         2.0       0.90      0.90      0.90        50
         3.0       0.94      0.85      0.89        40
         4.0       0.86      1.00      0.92        18

   micro avg       0.95      0.95      0.95       259
   macro avg       0.92      0.93      0.92       259
weighted avg       0.95      0.95      0.95       259



In [227]:
vect = TfidfVectorizer(stop_words='english')
sgdc = MultinomialNB()

pipe = Pipeline([('vect', vect), ('clf', sgdc)])
parameters = {
    'vect__max_df': (0.5, 0.75, 1.0),
    'clf__max_iter':(20, 10, 100)
}
grid_search = GridSearchCV(pipe,parameters, cv=5, n_jobs=-1, verbose=1)

grid_search.fit(train_clean['description'], train_clean['category'])
predictions = grid_search.predict(test['description']).astype(int)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:   15.8s finished
/Users/stephensinclair/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [228]:
predictions

array([2, 2, 4, 1, 1, 1, 1, 1, 2, 1, 4, 4, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 4, 1, 1, 1, 3, 1, 4, 2, 1, 1, 1, 1, 1, 3, 4, 3, 2, 1, 1, 3,
       1, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 4,
       2, 3, 1, 1, 1, 3, 1, 1, 4, 1, 3, 2, 1, 1, 4, 2, 2, 1, 1, 3, 2, 4,
       1, 3, 1, 1, 1, 1, 1, 4, 1, 1, 4, 3, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2,
       3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 2, 2, 4, 1, 1,
       1, 1, 3, 2, 1, 1, 1, 1, 1, 3, 2, 1, 1, 3, 4, 1, 1, 1, 3, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 4, 1, 1, 1, 3, 1, 2, 2, 1, 3, 3, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 4, 1, 3, 1, 4, 1, 1, 2, 2, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 4, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1,
       1, 4, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 3,
       2, 2, 1, 3, 1, 3, 3, 3, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 4, 1, 1, 1, 3,
       2, 1])

In [229]:
create_sub(predictions, 9)