<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Vector Representations
## *Data Science Unit 4 Sprint 2 Assignment 2*

In [1]:
import re
import string

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import spacy

In [2]:
import requests

In [6]:
from bs4 import BeautifulSoup

## 1) *Optional:* Scrape 100 Job Listings that contain the title "Data Scientist" from indeed.com

At a minimum your final dataframe of job listings should contain
- Job Title
- Job Description

If you choose to not to scrape the data, there is a CSV with outdated data in the directory. Remeber, if you scrape Indeed, you're helping yourself find a job. ;)

In [7]:
nlp = spacy.load('en_core_web_lg')

In [8]:
request = requests.get('https://www.indeed.co.uk/jobs?q=data+scientist&l=Greater+London')
soup = BeautifulSoup(request.text, 'html.parser')

In [11]:
def indexes_and_data(tag = 'None', class_name = 'None'):
      data = []
      #Runs if you only specify tag name
      if class_name == 'None':
        tag_list = soup.find_all(tag)
        for num in range(len(tag_list)):
          print("Index " + str(num) + ": " + tag_list[num].get_text())
          data.append(tag_list[num].get_text())
        return data
      #Runs if you only specify class name
      elif tag == 'None':
        tag_list = soup.find_all(class_ = class_name)
        for num in range(len(tag_list)):
          print("Index " + str(num) + ": " + tag_list[num].get_text())
          data.append(tag_list[num].get_text())
        return data
      #If using any of the above methods, make sure to specify parameters. 
      #Example indexes_and_data(tag= 'a') or indexes_and_data(class_name='whatever')

      #Runs if both tag name and class are specified
      #tag and class params don't need to be specified, Example indexes_and_data('a', 'whatever')
      else:
        tag_list = soup.find_all(tag, class_=class_name)
        for num in range(len(tag_list)):
          print("Index " + str(num) + ": " + tag_list[num].get_text())
          data.append(tag_list[num].get_text())
        return data

In [13]:
import urllib3

from bs4 import BeautifulSoup

URL = 'https://www.indeed.co.uk/jobs?q=data+scientist&l=Greater+London'


class IndeedScraper(object):
    """Get the long descriptions of Indeed.com job listings.

    You supply the base URL.

    Go to Indeed.com and enter the job-search term and city.
    Right click on the 'Find jobs' button and copy the link.
    Paste the link as an argument when instantiating the scraper.

    list_o_descriptions = IndeedScraper('http://www.indeed.com/jobs?q=data%20scientist&l=Seattle,%20WA').get_descriptions()

    :param url: string URL of job and city to search for.
    :param pages: int number of pages to scrape.
    :returns list: strings of job descriptions.

    """

    def __init__(self, url: str, pages: int):
        self.url = url
        self.http = urllib3.PoolManager()
        self.pages = pages

    def find_long_urls(self, soup):
        urls = []
        for div in soup.find_all(name='div', attrs={'class': 'row'}):
            for a in div.find_all(name='a', attrs={'class': 'jobtitle turnstileLink'}):
                urls.append(a['href'])
        return urls

    def get_next_pages(self):
        return [self.url] + [self.url +'&start='+ str(x) + '0' for x in range(1, self.pages)]

    def get_descriptions(self):
        descriptions = []
        for base_url in self.get_next_pages():
            request = self.http.request('GET',
                                        base_url)
            base_soup = BeautifulSoup(request.data)

            for url in self.find_long_urls(base_soup):
                the_url = "http://www.indeed.com/" + url

                req = self.http.request('GET', the_url,
                                        headers={'User-Agent': 'opera'},
                                        retries=urllib3.Retry(connect=500, read=2, redirect=50))

                soup = BeautifulSoup(req.data, 'html.parser')
                description = soup.find(name='div', attrs={'id': 'jobDescriptionText'})
                descriptions.append(description.text)

        return descriptions


get_em = IndeedScraper(URL, 10).get_descriptions()
print(get_em)

C:\Users\nikud\Anaconda3\envs\U4-S1-NLP\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\nikud\Anaconda3\envs\U4-S1-NLP\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\nikud\Anaconda3\envs\U4-S1-NLP\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\nikud\Anaconda3\envs\U4-S1-NLP\lib\site-packages\urllib3\c

["SummaryWe are looking for a motivated and high-achieving Data Scientist based in London to join a team commercialising the next-generation machine learning technology. This is a full-time placement with significant opportunities for personal development.We offer an intellectually stimulating environment, work within an interdisciplinary team and an inclusive culture. We are a high-calibre, mission-driven team building a technology that improves our World.The CompanyWe are on a mission to develop a machine that predicts the global economy in real-time. Our technology helps organisations plan and optimise business outcomes, thus improving efficiency and protecting the environment.causaLens wins 'Best Investment in Deeptech'. The scaling round was led by a top deep tech investor(see recent press FT, TechCrunch)causaLens in the 100 most disruptiveUK companiescausaLens in the Forbes'Top 15 Machine Learning Companies to watch in Europe'Core requirements: Strong academic record (MEng, MSci,

In [18]:
len(get_em)

190

In [16]:
doc = nlp(get_em[0])

print(token.lemma_ for token in doc if (token.is_stop !=True) and (token.is_punct != True))

<generator object <genexpr> at 0x00000235F307C228>


In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## 2) Use Spacy to tokenize / clean the listings 

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [22]:
vect = CountVectorizer()
vect.fit(get_em)
dtm = vect.transform(get_em)

In [21]:
print(vect.get_feature_names())

['00', '000', '00025', '000job', '000working', '0121', '02', '020', '03', '04', '05', '07', '08', '09', '10', '100', '1000', '101', '11', '110', '115', '11th', '12', '120', '125', '13', '130', '140', '1400', '140m', '142', '14m', '15', '158', '15billion', '16', '170', '18', '180', '1856', '19', '190', '19000kso', '1918', '1969', '1985', '1995', '1997', '19salary', '1st', '20', '200', '2000', '2002', '20072019job', '2010', '2011', '2012', '2014', '2015', '2016', '2017', '2018', '2019', '2019job', '2020', '204827', '210', '220', '23', '234', '24', '25', '25m', '26', '26240270', '27', '28', '29', '29th', '2bb', '2ht', '30', '300', '3192756', '3195005', '32', '33', '35', '36', '360', '37', '37½', '3job', '3rd', '40', '400', '410', '42', '42klsi', '434', '45', '450', '468', '4pm', '50', '500', '55', '57', '5dx', '60', '600', '640', '6489514', '65', '650', '6674', '68', '69', '70', '70m', '72', '737', '75', '750', '78', '80', '800', '803', '85', '8qs', '90', '919', '926', '930', 'aa', 'ab', 

In [23]:
dtm.todense()

matrix([[2, 2, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())
dtm.head()

00  000  00025  000job  000working  0121  02  020  03  04  ...  young  \
0   2    2      0       0           0     0   0    0   0   0  ...      0   
1   0    0      0       0           0     0   0    0   0   0  ...      0   
2   0    0      0       0           0     0   0    0   0   0  ...      0   
3   2    2      0       0           0     0   0    0   0   0  ...      0   
4   0    0      0       0           0     0   0    0   0   0  ...      0   

   your  youre  yourrecruitment  yourself  youtu  youtube  youyou  zeppelin  \
0     2      0                0         0      0        0       0         0   
1     0      0                0         0      0        0       1         0   
2     1      0                0         0      0        0       0         0   
3     1      0                0         0      0        0       0         0   
4     0      0                0         0      0        0       0         0   

   zoopla  
0       0  
1       0  
2       0  
3       0  
4       0  

[5 rows x 5538 columns]

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## 4) Visualize the most common word counts

In [25]:
vect = CountVectorizer(stop_words='english', min_df=.05, max_df=.9)
vect.fit(get_em)
dtm = vect.transform(get_em)
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())
dtm.head()

00  000  10  100  15  15billion  1985  2010  2011  2017  ...  world  \
0   2    2   0    1   1          0     0     0     0     0  ...      1   
1   0    0   0    0   0          0     0     0     1     0  ...      0   
2   0    0   0    0   0          0     0     0     0     0  ...      4   
3   2    2   0    1   1          0     0     0     0     0  ...      1   
4   0    0   0    0   0          0     0     0     0     0  ...      0   

   worldwide  write  writing  written  www  year  yearflexible  years  youyou  
0          0      0        0        1    0     1             0      0       0  
1          0      0        0        0    0     1             0      0       1  
2          0      0        0        0    1     0             0      0       0  
3          0      0        1        1    0     0             1      0       0  
4          0      0        0        1    0     0             0      0       0  

[5 rows x 1227 columns]

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## 5) Use Scikit-Learn's tfidfVectorizer to get a TF-IDF feature matrix

In [30]:

tfidf = TfidfVectorizer(stop_words = 'english')
sparse = tfidf.fit_transform(get_em)
dtm = pd.DataFrame(sparse.todense(), columns=tfidf.get_feature_names())
dtm.head()

00       000  00025  000job  000working  0121   02  020   03   04  \
0  0.105525  0.083789    0.0     0.0         0.0   0.0  0.0  0.0  0.0  0.0   
1  0.000000  0.000000    0.0     0.0         0.0   0.0  0.0  0.0  0.0  0.0   
2  0.000000  0.000000    0.0     0.0         0.0   0.0  0.0  0.0  0.0  0.0   
3  0.111850  0.088810    0.0     0.0         0.0   0.0  0.0  0.0  0.0  0.0   
4  0.000000  0.000000    0.0     0.0         0.0   0.0  0.0  0.0  0.0  0.0   

   ...  york  youey  young  youre  yourrecruitment  youtu  youtube    youyou  \
0  ...   0.0    0.0    0.0    0.0              0.0    0.0      0.0  0.000000   
1  ...   0.0    0.0    0.0    0.0              0.0    0.0      0.0  0.065565   
2  ...   0.0    0.0    0.0    0.0              0.0    0.0      0.0  0.000000   
3  ...   0.0    0.0    0.0    0.0              0.0    0.0      0.0  0.000000   
4  ...   0.0    0.0    0.0    0.0              0.0    0.0      0.0  0.000000   

   zeppelin  zoopla  
0       0.0     0.0  
1       0.0     0.0  
2       0.0     0.0  
3       0.0     0.0  
4       0.0     0.0  

[5 rows x 5297 columns]

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## 6) Create a NearestNeighbor Model. Write the description of your ideal datascience job and query your job listings. 

In [32]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [33]:
nn.kneighbors([dtm.iloc[0]])

(array([[0., 0., 0., 0., 0.]]), array([[ 0, 76, 19, 38, 58]], dtype=int64))

In [35]:
ideal_dsjob = ["""DESCRIPTION

Our Search and Analytics team is seeking an experienced applied science manager to lead a team of talented and passionate scientists. A successful candidate will have strong foundations in mathematics, statistics and machine learning with exceptional communication and leadership skills, and a proven track record of delivering research-based industrial systems under tight deadlines. As a Data Science Manager, you will lead a team of exceptional scientists to develop novel algorithms and modeling techniques that directly benefit our products and customers and advance the state of the art in Machine Learning, Information Extraction, Recommender Systems and Predictive Analytics.

 

BASIC QUALIFICATIONS

· A graduate degree in Computer Science, Electrical Engineering, Mathematics, Statistics, or a related field.
· 6+ years of industrial/academic research experience in data science, machine learning or a related field.
· 3+ years of experience leading R&D teams and a demonstrated track record of mentoring and developing junior team members.
· Demonstrated track record of applying Machine Learning algorithms to industrial research problems.
· Familiarity with Java or Scala

 

PREFERRED QUALIFICATIONS

· PhD degree in Computer Science, or a related discipline.
· More than 10 years of industrial/academic experience in building large-scale classification, information extraction, decision-support, or recommender systems in an industrial setting
· Demonstrated experience to manage an industrial research team for at least 3 years.
· Excellent written and verbal communication skills
· Solid track record of publishing original research in top-tier conferences and journals and filing patents

· Life sciences experience"""]

In [36]:
# Query
new = tfidf.transform(ideal_dsjob)

nn.kneighbors(new.todense())

(array([[1.27411084, 1.27411084, 1.27411084, 1.27411084, 1.27411084]]),
 array([[22, 78, 59,  4, 40]], dtype=int64))

In [37]:
# inspect the relevant result
get_em[22]

'Position SummaryThe data science team at Logically develops AI-first products (apps and services) that use machine learning to extract insights about news, misinformation, etc. This is mainly achieved through:Incubation of disruptive innovation (via scientists, engineers, and designers working together)Machine learning R&D (and publication in top AI/ML conferences and journals)The resulting solutions and innovations aim to reinvent Logically’s internal processes, improve the company’s offerings to its clients (in line with the company’s mission to be an ally for users in news consumption), and ultimately disrupt the wider news and the media industry.As a critical role in the technology division of the company, we are looking to hire computer vision scientists to join our team and contribute to the development and implementation of the algorithmic core of a series of exciting products/projects. This is an exciting opportunity for those who want to enjoy state-of-the-art R&D and be chal

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

## Stretch Goals

 - Try different visualizations for words and frequencies - what story do you want to tell with the data?
 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.
 - Create a labeled dataset - which jobs will you apply for? Train a model to select the jobs you are most likely to apply for. :) 