<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 1 Assignment 2*

# Document Representations: Bag-Of-Words

In [ ]:
import re
import string

!pip install -U nltk

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import sent_tokenize # Sentence Tokenizer
from nltk.tokenize import word_tokenize # Word Tokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.probability import FreqDist

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [6]:
data = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-4-Sprint-1-NLP/master/module2-vector-representations/job_listings.csv'

# 1) (optional) Scrape 100 Job Listings that contain the title "Data Scientist" from indeed.com

At a minimum your final dataframe of job listings should contain
- Job Title
- Job Description

If you choose to not to scrape the data, there is a CSV with outdated data in the directory. Remeber, if you scrape Indeed, you're helping yourself find a job. ;)

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task.")

In [29]:
df = pd.read_csv(data)

In [30]:
df['description'][0]

'b"<div><div>Job Requirements:</div><ul><li><p>\\nConceptual understanding in Machine Learning models like Nai\\xc2\\xa8ve Bayes, K-Means, SVM, Apriori, Linear/ Logistic Regression, Neural, Random Forests, Decision Trees, K-NN along with hands-on experience in at least 2 of them</p>\\n</li><li><p>Intermediate to expert level coding skills in Python/R. (Ability to write functions, clean and efficient data manipulation are mandatory for this role)</p>\\n</li><li><p>Exposure to packages like NumPy, SciPy, Pandas, Matplotlib etc in Python or GGPlot2, dplyr, tidyR in R</p>\\n</li><li><p>Ability to communicate Model findings to both Technical and Non-Technical stake holders</p>\\n</li><li><p>Hands on experience in SQL/Hive or similar programming language</p>\\n</li><li><p>Must show past work via GitHub, Kaggle or any other published article</p>\\n</li><li><p>Master\'s degree in Statistics/Mathematics/Computer Science or any other quant specific field.</p></li></ul><div><div><div><div><div><d

## 2) Use Spacy to tokenize / clean the listings 

In [31]:
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load("en")

tokenizer = Tokenizer(nlp.vocab)

In [32]:
tokens = []

"""make tokens"""
for doc in tokenizer.pipe(df['description'], batch_size=500):
    doc_tokens = [token.text for token in doc]
    tokens.append(doc_tokens)
    
df['tokens'] = tokens

In [48]:
data = list(df['tokens'])

# 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [55]:
vectorizer = CountVectorizer(stop_words='english')

vectorizer.fit(list(df['description']))

vectorizer.vocabulary_

dtm = vectorizer.transform(list(df['description']))

In [56]:
dtm.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 2, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]])

In [57]:
dtm = pd.DataFrame(dtm.todense(), columns = vectorizer.get_feature_names())

In [58]:
dtm.head()

00  000  02115  03  0356  04  057  062  06366  08  ...  zero  zeus  zf  \
0   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
1   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
2   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
3   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
4   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   

   zheng  zillow  zogsports  zones  zoom  zuckerberg  zurich  
0      0       0          0      0     0           0       0  
1      0       0          0      0     0           0       0  
2      0       0          0      0     0           0       0  
3      1       0          0      0     0           0       0  
4      0       0          0      0     0           0       0  

[5 rows x 9202 columns]

# 4) Visualize the most common word counts

In [63]:

def get_top_n_words(corpus, n=None):
    """
    List the top n words in a vocabulary according to occurrence in a text corpus.
    """
    vec = CountVectorizer(stop_words='english').fit(corpus)
    bag_of_words = vec.transform(corpus)
    sum_words = bag_of_words.sum(axis=0) 
    words_freq = [(word, sum_words[0, idx]) for word, idx in     vec.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1], reverse=True)
    return words_freq[:n]

In [65]:
get_top_n_words(df['description'])[:20]

[('li', 12785),
 ('and', 11746),
 ('to', 6931),
 ('div', 6870),
 ('the', 5397),
 ('of', 4612),
 ('data', 4452),
 ('br', 3894),
 ('in', 3614),
 ('with', 3070),
 ('ul', 2636),
 ('for', 2067),
 ('or', 1936),
 ('you', 1672),
 ('experience', 1584),
 ('we', 1522),
 ('our', 1508),
 ('is', 1451),
 ('xe2', 1417),
 ('x80', 1404)]

 # 5) Use Scikit-Learn's tfidfVectorizer to get a TF-IDF feature matrix

In [66]:
tfidf = TfidfVectorizer(stop_words='english', max_features=5000, min_df=.05)

In [67]:
dtm = tfidf.fit_transform(df['description'])

In [71]:
docs = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())
docs.head()

000   10  100  2019   40  abilities   ability  able  academic  access  ...  \
0  0.0  0.0  0.0   0.0  0.0        0.0  0.101507   0.0       0.0     0.0  ...   
1  0.0  0.0  0.0   0.0  0.0        0.0  0.019120   0.0       0.0     0.0  ...   
2  0.0  0.0  0.0   0.0  0.0        0.0  0.000000   0.0       0.0     0.0  ...   
3  0.0  0.0  0.0   0.0  0.0        0.0  0.000000   0.0       0.0     0.0  ...   
4  0.0  0.0  0.0   0.0  0.0        0.0  0.000000   0.0       0.0     0.0  ...   

   x99ll     x99re    x99s  x99t  x9d       xe2        xs      year     years  \
0    0.0  0.000000  0.0000   0.0  0.0  0.000000  0.000000  0.000000  0.000000   
1    0.0  0.067365  0.0352   0.0  0.0  0.119005  0.000000  0.032782  0.000000   
2    0.0  0.000000  0.0000   0.0  0.0  0.000000  0.000000  0.000000  0.000000   
3    0.0  0.000000  0.0000   0.0  0.0  0.000000  0.325896  0.069212  0.000000   
4    0.0  0.000000  0.0000   0.0  0.0  0.083943  0.000000  0.000000  0.091059   

   york  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  

[5 rows x 1003 columns]

 # 6) Create a NearestNeighbor Model. Write the description of your ideal datascience job and query your job listings. 

In [75]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')

nn.fit(dtm.todense())

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [82]:
ideal_job_description = ["We’re looking for a data scientist with a passion for tackling big problems. A member of our Predictive Modeling team, you will be embedded in our Advocate Center with a mission to identify opportunities to apply your unique skillset, ensure confidence in your products and promote their adoption among our Advocate teams. Your predictive models will inform decisions and drive real-time strategy in this critical area. You will have the opportunity to work with a top-caliber team of former professors and PhDs, develop insights from a large array of proprietary datasets, and apply cutting edge methods in machine learning, experimental design, simulation and optimization, and statistics. Most importantly, you will have the satisfaction of working side-by-side with our advocates and witnessing the direct impact your products have as they use them to enhance the customer experience."]

In [83]:
new = tfidf.transform(ideal_job_description)

nn.kneighbors(new.todense())

(array([[1.23109268, 1.23109268, 1.25836823, 1.26230218, 1.26270597]]),
 array([[142,  52,  36, 404, 342]]))

In [86]:
df['description'][36]

"b'<div><p><b>Position Summary\\n</b></p><p></p>In today\\xe2\\x80\\x99s fast evolving technology world, one aspect remains common \\xe2\\x80\\x93 reliance on data to drive the next wave of innovation. Strategic Analytics is Samsung\\xe2\\x80\\x99s Center-of-Excellence for driving the adoption of data driven decision making and product development across the company. The team\\xe2\\x80\\x99s core focus is developing best-in-class solutions that provide Samsung\\xe2\\x80\\x99s marketing and service organizations with a 360 degree view of the Samsung customers.\\n<br/>\\n<br/>\\nStrategic Analytics is powering a paradigm shift at Samsung and the global industry. We are looking for highly technical team members who are passionate about data, have the rigor needed to solve billion dollar problems, and possess an innate entrepreneurial spirit to explore the uncharted. Strategic Analytics combines the engineering backbone of a best-in-class Big Data Platform with the analytic expertise of ad

## Stretch Goals

 - Try different visualizations for words and frequencies - what story do you want to tell with the data?
 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.