<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Vector Representations
## *Data Science Unit 4 Sprint 2 Assignment 2*

In [352]:
import re
import string

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import spacy

from bs4 import BeautifulSoup

from spacy.tokenizer import Tokenizer

## 1) *Clean:* Job Listings from indeed.com that contain the title "Data Scientist" 

You have `job_listings.csv` in the data folder for this module. The text data in the description column is still messy - full of html tags. Use the [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) library to clean up this column. You will need to read through the documentation to accomplish this task. 

In [338]:
from bs4 import BeautifulSoup
import requests

jobs = pd.read_csv("data/job_listings.csv")

jobs.head(20)

jobs = jobs.drop(columns='Unnamed: 0')

##### Your Code Here #####
#raise Exception("\nThis task is not complete. \nReplace this line with your code for the task.")
                


In [339]:
jobs

###OK now I need to use Beautiful Soup to parse the words.

description  \
0    b"<div><div>Job Requirements:</div><ul><li><p>...   
1    b'<div>Job Description<br/>\n<br/>\n<p>As a Da...   
2    b'<div><p>As a Data Scientist you will be work...   
3    b'<div class="jobsearch-JobMetadataHeader icl-...   
4    b'<ul><li>Location: USA \xe2\x80\x93 multiple ...   
..                                                 ...   
421  b"<b>About Us:</b><br/>\nWant to be part of a ...   
422  b'<div class="jobsearch-JobMetadataHeader icl-...   
423  b'<div class="jobsearch-JobMetadataHeader icl-...   
424  b"<p></p><div><p>SENIOR DATA SCIENTIST</p><p>\...   
425  b'<div></div><div><div><div><div><p>Cerner Int...   

                                                 title  
0                                      Data scientist   
1                                     Data Scientist I  
2                         Data Scientist - Entry Level  
3                                       Data Scientist  
4                                       Data Scientist  
..                                                 ...  
421                       Senior Data Science Engineer  
422  2019 PhD Data Scientist Internship - Forecasti...  
423                         Data Scientist - Insurance  
424                              Senior Data Scientist  
425                                     Data Scientist  

[426 rows x 2 columns]

In [340]:
def clean_description(desc):
    soup = BeautifulSoup(desc)
    #soup = soup.stripped_strings
    soup = soup.get_text()
    soup = soup.replace("\\n", "")

    
        #strip=True
    return soup

In [341]:
jobs['clean_desc'] = jobs['description'].apply(clean_description)

In [342]:
jobs['description'][5]

"b'<div>Create various Business Intelligence Analytical reports, visualization and dashboards with BI tools like Tableau, Power BI or similar;<br/>\\nUtilize experience in scientific data, logic programming and calculated columns, and decision making;<br/>\\nDevelop and maintain dashboards for KPIs, purchase trends with time series and customer flows with Tableau and Teradata;<br/>\\nDevelop recommendation models utilizing machine learning and predictive analysis with supervised and unsupervised algorithms like random forest, support vector machine and k-means clustering;<br/>\\nUtilize experience with SQL with strong concepts of database, data warehouse and metadata;<br/>\\nWork closely with frontend web developer and UX designer on improving online shopping experience and deploying business strategies like promotion or similar;<br/>\\nAnalyze customer behaviors and purchase trends to create customized recommended items;<br/>\\nConduct and apply A/B test to monitor and test new or mod

In [343]:
jobs['clean_desc'][5]

"b'Create various Business Intelligence Analytical reports, visualization and dashboards with BI tools like Tableau, Power BI or similar;Utilize experience in scientific data, logic programming and calculated columns, and decision making;Develop and maintain dashboards for KPIs, purchase trends with time series and customer flows with Tableau and Teradata;Develop recommendation models utilizing machine learning and predictive analysis with supervised and unsupervised algorithms like random forest, support vector machine and k-means clustering;Utilize experience with SQL with strong concepts of database, data warehouse and metadata;Work closely with frontend web developer and UX designer on improving online shopping experience and deploying business strategies like promotion or similar;Analyze customer behaviors and purchase trends to create customized recommended items;Conduct and apply A/B test to monitor and test new or modified features for online shopping experiences across desktop

## 2) Use Spacy to tokenize the listings 

In [353]:
##### Your Code Here #####
#raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

nlp = spacy.load('en_core_web_lg')

tokenizer = Tokenizer(nlp.vocab)

tokens = []

for doc in tokenizer.pipe(jobs['clean_desc'], batch_size=500):
    doc_tokens = [token.text for token in doc]
    tokens.append(doc_tokens)

jobs['clean_desc_token'] = tokens

In [356]:
jobs['clean_desc_token'][0]

['b"Job',
 'Requirements:Conceptual',
 'understanding',
 'in',
 'Machine',
 'Learning',
 'models',
 'like',
 'Nai\\xc2\\xa8ve',
 'Bayes,',
 'K-Means,',
 'SVM,',
 'Apriori,',
 'Linear/',
 'Logistic',
 'Regression,',
 'Neural,',
 'Random',
 'Forests,',
 'Decision',
 'Trees,',
 'K-NN',
 'along',
 'with',
 'hands-on',
 'experience',
 'in',
 'at',
 'least',
 '2',
 'of',
 'themIntermediate',
 'to',
 'expert',
 'level',
 'coding',
 'skills',
 'in',
 'Python/R.',
 '(Ability',
 'to',
 'write',
 'functions,',
 'clean',
 'and',
 'efficient',
 'data',
 'manipulation',
 'are',
 'mandatory',
 'for',
 'this',
 'role)Exposure',
 'to',
 'packages',
 'like',
 'NumPy,',
 'SciPy,',
 'Pandas,',
 'Matplotlib',
 'etc',
 'in',
 'Python',
 'or',
 'GGPlot2,',
 'dplyr,',
 'tidyR',
 'in',
 'RAbility',
 'to',
 'communicate',
 'Model',
 'findings',
 'to',
 'both',
 'Technical',
 'and',
 'Non-Technical',
 'stake',
 'holdersHands',
 'on',
 'experience',
 'in',
 'SQL/Hive',
 'or',
 'similar',
 'programming',
 'languag

In [357]:
type(jobs['description'][0])

str

In [358]:
type(jobs['clean_desc'][0])

str

In [361]:
type(jobs['clean_desc_token'][0])

list

In [349]:
#jobs['clean_desc'][9]

## 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [ ]:
### Can just plug in the whole pandas series (df column) into the vectorizer


In [366]:
jobs['clean_desc_token'][100]

['b"DescriptionA',
 'rare',
 'opportunity',
 'to',
 'join',
 'the',
 'development',
 'division',
 'within',
 'Information',
 'Systems',
 'at',
 'Steward',
 'Health',
 'Care,',
 'the',
 'top',
 'leader',
 'in',
 'the',
 'competitive',
 'for-profit',
 'hospital',
 'industry.',
 'We',
 'are',
 'seeking',
 'a',
 'motivated',
 'and',
 'experienced',
 'Data',
 'Scientist',
 'to',
 'contribute',
 'to',
 'the',
 'software',
 'development',
 'initiatives',
 'that',
 'improve',
 'the',
 'quality',
 'of',
 'health',
 'care',
 'across',
 'the',
 'country.',
 'This',
 'individual',
 'will',
 'be',
 'working',
 'with',
 'programmers,',
 'analysts',
 'and',
 'senior',
 'level',
 'management',
 'to',
 'optimize',
 'the',
 'development',
 'process',
 'within',
 'the',
 'enterprise',
 'by',
 'expanding',
 'our',
 'existing',
 'predictive',
 'analytics',
 'field.Key',
 'ResponsibilitiesConduct',
 'research',
 'and',
 'build',
 'actionable',
 'visualizations',
 'that',
 'drive',
 'decisions.Collect',
 'da

In [367]:
#jobs_data = jobs['clean_desc_token']

#This creates a list, which vectorize doesn't like

In [375]:
type(jobs['clean_desc_token'][0])

list

In [377]:
jobs_data = jobs['clean_desc']


In [378]:
vect = CountVectorizer()

vect.fit(jobs_data)

dtm = vect.transform(jobs_data)

In [379]:
dtm

<426x12061 sparse matrix of type '<class 'numpy.int64'>'
	with 112033 stored elements in Compressed Sparse Row format>

In [382]:
len(vect.get_feature_names())

12061

In [386]:
text[:30]

b"Job Requirements:Conceptual understanding in Machine Learning models like Nai\xc2\xa8ve Bayes, K-Means, SVM, Apriori, Linear/ Logistic Regression, Neural, Random Forests,

In [391]:
#print(dtm
dtm.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 2, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]])

In [392]:
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())
dtm

00  000  000pay  02115job  03  0356  04  062  06366  08  ...  zenreach  \
0     0    0       0         0   0     0   0    0      0   0  ...         0   
1     0    0       0         0   0     0   0    0      0   0  ...         0   
2     0    0       0         0   0     0   0    0      0   0  ...         0   
3     0    0       0         0   0     0   0    0      0   0  ...         0   
4     0    0       0         0   0     0   0    0      0   0  ...         0   
..   ..  ...     ...       ...  ..   ...  ..  ...    ...  ..  ...       ...   
421   0    0       0         0   0     0   0    0      0   0  ...         0   
422   0    0       0         0   0     0   0    0      0   0  ...         0   
423   0    2       0         0   0     0   0    0      0   0  ...         0   
424   0    0       0         0   0     0   0    0      0   0  ...         0   
425   0    1       0         0   0     0   0    0      0   0  ...         0   

     zero  zeus  zf  zheng  zillow  zonesability  zoom  zuckerberg  zurich  
0       0     0   0      0       0             0     0           0       0  
1       0     0   0      0       0             0     0           0       0  
2       0     0   0      0       0             0     0           0       0  
3       0     0   0      1       0             0     0           0       0  
4       0     0   0      0       0             0     0           0       0  
..    ...   ...  ..    ...     ...           ...   ...         ...     ...  
421     0     0   0      0       0             0     0           0       0  
422     0     0   0      0       0             0     0           0       0  
423     1     0   0      0       0             0     0           0       0  
424     0     0   0      0       0             0     0           0       0  
425     0     0   0      0       0             0     0           0       0  

[426 rows x 12061 columns]

## 4) Visualize the most common word counts

In [408]:
top_20_words = dtm.sum().sort_values(ascending=False).head(20)
top_20_words

and           11727
to             6924
the            5427
of             4606
data           4346
in             3618
with           3061
for            2065
or             1931
you            1722
we             1598
our            1538
is             1448
xe2            1417
x80            1404
experience     1384
will           1315
as             1248
on             1204
business       1172
dtype: int64

In [404]:
#result.describe()

In [409]:
#top_20_word_counts = result.count().sort_values(ascending=False).head(20)

#top_20_word_counts


## 5) Use Scikit-Learn's tfidfVectorizer to get a TF-IDF feature matrix

In [421]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

# Create a vocabulary and get word counts per document
# Similiar to fit_predict
dtm = tfidf.fit_transform(jobs_data)

# Print word counts

# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

# View Feature Matrix as DataFrame
dtm.head(20)

000   04   10       100  1079302who   11   12  125   14   15  ...  \
0   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
1   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
2   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
3   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
4   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
5   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
6   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
7   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
8   0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
9   0.000000  0.0  0.0  0.042607         0.0  0.0  0.0  0.0  0.0  0.0  ...   
10  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
11  0.077232  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
12  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
13  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
14  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
15  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
16  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
17  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
18  0.000000  0.0  0.0  0.000000         0.0  0.0  0.0  0.0  0.0  0.0  ...   
19  0.334631  0.0  0.0  0.165942         0.0  0.0  0.0  0.0  0.0  0.0  ...   

    young    youyou  yrs  zenreach  zero  zeus   zf  zillow  zuckerberg  \
0     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
1     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
2     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
3     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
4     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
5     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
6     0.0  0.096882  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
7     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
8     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
9     0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
10    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
11    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
12    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
13    0.0  0.096882  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
14    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
15    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
16    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
17    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
18    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   
19    0.0  0.000000  0.0       0.0   0.0   0.0  0.0     0.0         0.0   

    zurich  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
5      0.0  
6      0.0  
7      0.0  
8      0.0  
9      0.0  
10     0.0  
11     0.0  
12     0.0  
13     0.0  
14     0.0  
15     0.0  
16     0.0  
17     0.0  
18     0.0  
19     0.0  

[20 rows x 5000 columns]

In [420]:
dtm.shape

(426, 5000)

## 6) Create a NearestNeighbor Model. Write the description of your ideal datascience job and query your job listings. 

In [422]:
from sklearn.neighbors import NearestNeighbors

In [423]:
nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [424]:
nn.kneighbors([dtm.iloc[0].values])

(array([[0.        , 1.28956338, 1.29087035, 1.295877  , 1.29730159]]),
 array([[  0, 274, 366, 338, 115]]))

In [432]:
nn.kneighbors([dtm.iloc[100]])

(array([[0.        , 0.        , 1.20894849, 1.23852435, 1.24256154]]),
 array([[ 47, 100, 201, 307, 147]]))

In [433]:
jobs_data[100][:500]

'b"DescriptionA rare opportunity to join the development division within Information Systems at Steward Health Care, the top leader in the competitive for-profit hospital industry. We are seeking a motivated and experienced Data Scientist to contribute to the software development initiatives that improve the quality of health care across the country. This individual will be working with programmers, analysts and senior level management to optimize the development process within the enterprise by '

In [435]:
jobs_data[201][:500]

"b'InternshipOverviewData Science InternshipsPortland, OR or Seattle, WAThese twelve-week internships are scheduled to begin in May/June 2019Responsibilities & RequirementsCambia Health Solutions is working to create a seamless and frictionless health care experience for consumers nationwide. This presents a unique challenge and opportunity for innovative and disruptive solutions from our Artificial Intelligence team.Our Data Scientists design, develop, and implement data-driven solutions using m"

In [ ]:
### Nice, these seem like similar job descriptions!

In [451]:
### Writing my own job description:

wills_jd = ["""
This job is about 10% programming, 10% visual art, and 80% chilling.
Every day you will research solutions to the climate crisis, while also having plenty of time to hike outside.
We will pay a salary of $1M per year, and only require you to be in the office one week per month.
You will have awesome co-workers who are as excited about this opportunity as you are.
You need to know Python, pandas, artificial general intelligence, and machine learning. 
The ideal candidate also enjoys kayaking, skiing, and paragliding.
Keywords: climate change, environmental science, hydrology, earth science, geology, geomorphology
Other keywords: GIS, geospatial analysis, AI
"""]

In [452]:
new = tfidf.transform(wills_jd)
new

<1x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [453]:
nn.kneighbors(new.todense())

(array([[1.29527379, 1.31123947, 1.32754159, 1.32754159, 1.32880595]]),
 array([[306,  84, 315, 207, 255]]))

In [456]:
jobs_data[306]

"b'Please review the job details below.Radiant Solutions is growing and we are looking for motivated data evangelists who are passionate about delivering new and innovative solutions for our customers. The ideal candidate needs limited direction, is passionate about technology and is curious about earth sensing and the new space economy.What you\\'ll get to do:You will be applying the latest machine learning techniques to extract insights from geospatial data.You will have access to an enormous corpus of training data and will work to build the best models through bake-offs, hyperparameter searching, and incremental learning techniques.You will quantitatively assess model performance and document the overall life-cycle.You will work with other members of the data science and engineering teams to improve data science products and experiences.Additionally, you will be developing rapid prototype solutions as needed for the focused collection, parsing, managing, analyzing, and visualizing 

In [ ]:
## Hey, this job sounds cool!

# eveything below this is garbage

In [368]:
#This attempt isn't as clean
'''
def vectorize(text):
    vect.fit(text)
    dtm = vect.transform(text)
    return dtm

def vectorize_str(text):
    vect.fit([text])
    dtm = vect.transform([text])
    return dtm 
'''

'\ndef vectorize(text):\n    vect.fit(text)\n    dtm = vect.transform(text)\n    return dtm\n\ndef vectorize_str(text):\n    vect.fit([text])\n    dtm = vect.transform([text])\n    return dtm \n'

In [395]:
#vectorized_description_1 = vectorize_str(jobs['description'][0])

#vectorized_description_1

In [396]:
#dtm = pd.DataFrame(vectorized_description_1.todense(), columns=vect.get_feature_names())
#dtm["description"] = jobs['description'][0]

#dtm

In [397]:
#vectorized_description_2 = vectorize_str(jobs['description'][1])

#vectorized_description_2

In [398]:
#dtm2 = pd.DataFrame(vectorized_description_2.todense(), columns=vect.get_feature_names())
#dtm2["description"] = jobs['description'][1]

In [399]:
#result = pd.concat([dtm, dtm2], axis=0, sort=False)
#result

In [400]:
#range(len(jobs['description']))

In [259]:
#type(jobs_dtms)

list

In [401]:
"""
jobs_dtms = []

for row in range(len(jobs['description'])):
#for row in range(5):
    vectorized_description = vectorize_str(jobs['description'][row])
    dtm = pd.DataFrame(vectorized_description.todense(), columns=vect.get_feature_names())
    dtm["description"] = jobs['description'][row]
    dtm["title"] = jobs['title'][row]
    
    jobs_dtms.append(dtm)
    
result = pd.concat(jobs_dtms, axis=0, sort=False)
result
"""


'\njobs_dtms = []\n\nfor row in range(len(jobs[\'description\'])):\n#for row in range(5):\n    vectorized_description = vectorize_str(jobs[\'description\'][row])\n    dtm = pd.DataFrame(vectorized_description.todense(), columns=vect.get_feature_names())\n    dtm["description"] = jobs[\'description\'][row]\n    dtm["title"] = jobs[\'title\'][row]\n    \n    jobs_dtms.append(dtm)\n    \nresult = pd.concat(jobs_dtms, axis=0, sort=False)\nresult\n'

In [275]:
#result.describe()

In [276]:
#dtm = jobs['description'].apply(vectorize_str)

In [277]:
#type(dtm[0])

In [278]:
#dtm[0].todense().shape

In [279]:
#print(dtm[0])

#dtm[0].shape

In [280]:
#dtm = pd.DataFrame(dtm[0].todense(), columns=vect.get_feature_names())
#dtm

In [281]:
#type(jobs['description'][0])

In [282]:
#type(jobs['clean_desc_list'][0])

In [283]:
##workflow for one row

#token_text = jobs['clean_desc_list'][0]

#token_text

In [284]:
#token_text = [token_text]

#type(token_text)

In [285]:
#og_text = jobs['description'][0]
#og_text

In [286]:
#og_text = [og_text]
#vectorize(og_text)

In [287]:
#vect.get_feature_names()

In [288]:
#og_text[:20]

In [289]:
#dtm = vectorize(og_text)
#dtm

In [290]:
#dtm.todense()

In [291]:
#dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())
#dtm

In [292]:
#for item in jobs['description']:
#    item = [item]

In [293]:
#type(jobs['description'][0])

In [294]:
#jobs['description'][0]

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [335]:
#result.shape

(426, 9455)

## Stretch Goals

 - Try different visualizations for words and frequencies - what story do you want to tell with the data?
 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.
 - Create a labeled dataset - which jobs will you apply for? Train a model to select the jobs you are most likely to apply for. :) 