<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Sprint Challenge
## *Data Science Unit 4 Sprint 1*

After a week of Natural Language Processing, you've learned some cool new stuff: how to process text, how turn text into vectors, and how to model topics from documents. Apply your newly acquired skills to one of the most famous NLP datasets out there: [Yelp](https://www.yelp.com/dataset/challenge). As part of the job selection process, some of my friends have been asked to create analysis of this dataset, so I want to empower you to have a head start.  

The real dataset is massive (almost 8 gigs uncompressed). I've sampled the data for you to something more managable for the Sprint Challenge. You can analyze the full dataset as a stretch goal or after the sprint challenge. As you work on the challenge, I suggest adding notes about your findings and things you want to analyze in the future.

## Challenge Objectives
*Successfully complete these all these objectives to earn a 2. There are more details on each objective further down in the notebook.*
* <a href="#p1">Part 1</a>: Write a function to tokenize the yelp reviews
* <a href="#p2">Part 2</a>: Create a vector representation of those tokens
* <a href="#p3">Part 3</a>: Use your tokens in a classification model on yelp rating
* <a href="#p4">Part 4</a>: Estimate & Interpret a topic model of the Yelp reviews

In [1]:
import pandas as pd

yelp = pd.read_json('./data/review_sample.json', lines=True)

In [2]:
yelp.head()

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id  
0  n1LM36qNg4rqGXIcvVXv8w  
1  5CgjjDAic2-FAvCtiHpytA  
2  BdV-cf3LScmb8kZ7iiBcMA  
3  cZZnBqh4gAEy4CdNvJailQ  
4  n9QO4ClYAS7h9fpQwa5bhA

## Part 1: Tokenize Function
<a id="#p1"></a>

Complete the function `tokenize`. Your function should
- accept one document at a time
- return a list of tokens

You are free to use any method you have learned this week.

In [54]:
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS

In [55]:
# extend stopwords to include extremely common words specific to the works
STOPWORDS = set(STOPWORDS).union(set(['food', 'place', 'time', ]))

def tokenize(doc):
    '''
    tokenizer
    '''  
    return [token for token in simple_preprocess(doc) if token not in STOPWORDS]

In [56]:
def create_df(df):
    '''
    tokenize and keep only key columns
    '''
    df2 = df.copy()
    df2['tokens'] = df2['text'].apply(tokenize)
    return df2

yelp = create_df(yelp)
yelp.head()    

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id                                             tokens  
0  n1LM36qNg4rqGXIcvVXv8w  [beware, fake, fake, fake, small, business, lo...  
1  5CgjjDAic2-FAvCtiHpytA  [came, lunch, togo, service, quick, staff, fri...  
2  BdV-cf3LScmb8kZ7iiBcMA  [ve, vegas, dozens, times, stepped, foot, circ...  
3  cZZnBqh4gAEy4CdNvJailQ  [went, night, closed, street, party, best, act...  
4  n9QO4ClYAS7h9fpQwa5bhA  [stars, bad, price, lunch, seniors, pay, eatin...

## Part 2: Vector Representation
<a id="#p2"></a>
1. Create a vector representation of the reviews
2. Write a fake review and query for the 10 most similiar reviews, print the text of the reviews. Do you notice any patterns?
    - Given the size of the dataset, it will probably be best to use a `NearestNeighbors` model for this. 

In [78]:
from sklearn.feature_extraction.text import CountVectorizer

data = yelp['text']

# instantiate count
vect = CountVectorizer(stop_words='english', min_df = 0.05, max_df= 0.90)

# tokenize and build vocab
vect.fit(data)

# transform text
sparse_dtm = vect.transform(data)

dtm = pd.DataFrame(sparse_dtm.todense(), columns=vect.get_feature_names())

In [79]:
dtm.head()

10  amazing  area  asked  away  awesome  bad  bar  best  better  ...  \
0   0        0     0      0     0        0    0    0     0       0  ...   
1   0        0     0      0     0        0    0    0     0       0  ...   
2   0        0     1      0     0        0    0    0     0       0  ...   
3   0        0     0      0     0        0    0    0     1       0  ...   
4   0        0     0      0     0        0    1    2     0       0  ...   

   vegas  wait  want  wanted  wasn  way  went  work  worth  years  
0      0     1     0       0     0    0     0     0      0      0  
1      0     0     0       0     0    0     0     0      0      0  
2      2     0     0       0     0    0     1     0      0      0  
3      0     0     0       0     0    0     1     0      0      0  
4      0     0     0       0     0    0     0     0      0      0  

[5 rows x 116 columns]

In [80]:
# Instantiate
from sklearn.neighbors import NearestNeighbors

# Fit on Vectors
nn  = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [81]:
sample_review = ["""We have never had such awful service. They first mixed up our order with another table's, then the food came out cold, there was a bug in it, the drinks never arrived. our reservation was not honoured. I will not be returning here again."""]


In [82]:
# Query for Sim of Random doc to Yelp
new = vect.transform(sample_review)

nn.kneighbors(new.todense())

(array([[1.73205081, 2.        , 2.        , 2.        , 2.        ]]),
 array([[1986, 1104, 2895, 7242,  829]]))

In [83]:
# inspect most relevant result
data[1986]

'While the food and drinks are okay the service is virtually nonexistent.'

## Part 3: Classification
<a id="#p3"></a>
Your goal in this section will be to predict `stars` from the review dataset. 

1. Create a piepline object with a sklearn `CountVectorizer` or `TfidfVector` and any sklearn classifier. Use that pipeline to estimate a model to predict `stars`. Use the Pipeline to predict a star rating for your fake review from Part 2. 
2. Tune the entire pipeline with a GridSearch

In [63]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [84]:
parameters = {
    'vect__max_df': ( 0.75, 1.0),
    'vect__min_df': (.02, .05),
    'vect__max_features': (500,1000),
    'clf__n_estimators':(5, 10,),
    'clf__max_depth':(15,20)
}

In [85]:
# define pipeline components 

# note: vec can be any Tfidf or Count Vectorizer
vect = CountVectorizer(stop_words='english', min_df = 0.05, max_df= 0.90)
rfc = RandomForestClassifier()

pipe = Pipeline([('vect', vect), ('clf', rfc)])

In [86]:
grid_search = GridSearchCV(pipe, parameters, cv=5, n_jobs=4, verbose=1)
grid_search.fit(yelp['text'], yelp['stars'])

Fitting 5 folds for each of 32 candidates, totalling 160 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:   47.5s
[Parallel(n_jobs=4)]: Done 160 out of 160 | elapsed:  2.8min finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.9, max_features=None, min_df=0.05,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
     ...obs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))]),
       fit_params=None, iid='warn', n_jobs=4,
       param_grid={'vect__max_df': (0.75, 1.0), 'vect__min_df': (0.02, 0.05), 'vect__max_features': (500, 1000), 'clf__n_estimators': (5, 10), 'clf__max_depth': (15, 20)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [118]:
grid_search.predict(["'We have never had such awful service. They first mixed up our order with another table's, then the food came out cold, there was a bug in it, the drinks never arrived. our reservation was not honoured. I will not be returning here again.'"])

array([1])

## Part 4: Topic Modeling

Let's find out what those yelp reviews are saying! :D

1. Estimate a LDA topic model of the review text
    - Keep the `iterations` parameter at or below 5 to reduce run time
    - The `workers` parameter should match the number of physical cores on your machine.
2. Create 1-2 visualizations of the results
    - You can use the most important 3 words of a topic in relevant visualizations. Refer to yesterday's notebook to extract. 
3. In markdown, write 1-2 paragraphs of analysis on the results of your topic model

__*Note*__: You can pass the DataFrame column of text reviews to gensim. You do not have to use a generator.

In [119]:
from gensim.models import LdaMulticore
from gensim.corpora import Dictionary

from gensim import corpora

from gensim.models.ldamulticore import LdaMulticore

Learn the vocubalary of the yelp data:

In [120]:
id2word = corpora.Dictionary(yelp['tokens'])


Create a bag of words representation of the entire corpus

In [121]:
corpus = [id2word.doc2bow(text) for text in yelp['tokens']]


Your LDA model should be ready for estimation: 

In [122]:
import warnings
warnings.filterwarnings('ignore')

lda = LdaMulticore(corpus=corpus,
                   id2word=id2word,
                   iterations=3,
                   workers=4,
                   num_topics = 10 # You can change this parameter
                  )

Create 1-2 visualizations of the results

In [123]:
import pyLDAvis.gensim

pyLDAvis.enable_notebook()

In [ ]:
# evaluate the model
pyLDAvis.gensim.prepare(lda, corpus, id2word)

In [ ]:
# each topic has a different distribution of the same "stock" of words
lda.print_topics()

In [ ]:
import re
# use regex to remove the non-text components
words = [re.findall(r'"([^"]*)"',t[1]) for t in lda.print_topics()]

In [ ]:
# top 10 words
topics = [' '.join(t[0:10]) for t in words]

In [ ]:
# print out nicely 
for id, t in enumerate(topics): 
    print(f"------ Topic {id} ------")
    print(t, end="\n\n")

## Analysis:

A lot of reviews use generic terms like 'food', 'great', 'service' to describe their experiences. 

I think this is indicative of how reviews are weighted towards negative experiences. A postive experience is less likely to be reported at all, and if it is, reviews use the generic terms listed above. A negative experience is more likely to be reported and elaborated on at length with specifics of what did not meet expectations. 

Hence, as an analysis of how frequent words appear, more positive or generic words appear more frequently than compared to the large variatation in words chosen for negative reviews. 




## Stretch Goals

Complete one of more of these to push your score towards a three: 
* Incorporate named entity recognition into your analysis
* Compare vectorization methods in the classification section
* Analyze more (or all) of the yelp dataset - this one is v. hard. 
* Use a generator object on the reviews file - this would help you with the analyzing the whole dataset.
* Incorporate any of the other yelp dataset entities in your analysis (business, users, etc.)